compiler_pass:
    dashboard_widget:
        path: '@enhavo/app/compiler-pass/model-factory-register.js'
        service: '@enhavo/dashboard/dashboard/DashboardWidgetFactory'
        tag: 'enhavo_dashboard.widget'

services:
    '@enhavo/dashboard/manager/DashboardManager':
        import: DashboardManager
        arguments:
            - '@enhavo/app/frame/FrameManager'
            - '@enhavo/dashboard/dashboard/DashboardWidgetManager'
            - '@enhavo/app/routing/Router'
        tags:
            - { name: vue.service, service: 'dashboardManager', reactive: true }

    '@enhavo/dashboard/dashboard/DashboardWidgetFactory':
        import: DashboardWidgetFactory
        chunk: 'column'

    '@enhavo/dashboard/dashboard/DashboardWidgetManager':
        import: DashboardWidgetManager
        arguments:
            - '@enhavo/dashboard/dashboard/DashboardWidgetFactory'

    '@enhavo/dashboard/dashboard/model/BaseDashboardWidget':
        import: BaseDashboardWidget
        tags:
            - 'enhavo_dashboard.widget'

    '@enhavo/dashboard/dashboard/model/NumberDashboardWidget':
        import: NumberDashboardWidget
        tags:
            - 'enhavo_dashboard.widget'

    '@enhavo/dashboard/components/DashboardIndex.vue':
        static: true
        tags:
            - { name: vue.component, component: 'dashboard-index' }

    '@enhavo/dashboard/components/DashboardWidgetNumber.vue':
        static: true
        tags:
            - { name: vue.component, component: 'dashboard-widget-number' }
